import type { Metadata } from "next";
import "./globals.css";
import TransparentHeader from "@/src/Header";

export const metadata: Metadata = {
  title: "İsim",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
    <body>
      <div className="flex min-h-screen">
        <div className="flex-1">
          <header className="z-30 hidden sm:flex">
            <TransparentHeader />
          </header>
          <main className="flex-1">{children}</main>
        </div>
      </div>
    </body>
  </html>
  );
}
